### ISSUE TITLE
ring.middleware.x-headers not supported

### ISSUE THREAD

**Issue by camdez** [muhuk/aleph-middleware#1]
`ring.middleware.x-headers` provides the follow three middlewares:
- `wrap-content-type-options`
- `wrap-frame-options`
- `wrap-xss-protection`

These are even used from `ring.middleware.defaults/site-defaults`, so (I feel) they're pretty important to support.

**Comment by camdez** [comment]
My mistake. I see now that this middleware doesn't ship with Ring. If you have any thoughts about the best way to handle some of these common middleware which don't ship with Ring, and share that work back to to community, I'd love to hear it. Closing.

**Comment by muhuk** [comment]
Hi @camdez ,

(This is also a response to #2 )

I think the cleanest way to get those 3rd party middleware to support Aleph is in their own packages.

Aleph stuff (and dependency) can be optional. There is an example of how it can be done [here](https://github.com/muhuk/ring-transit-middleware/blob/89686e90d1cfdfbc64d1d142f4047e208720b902/src/ring/middleware/transit.clj#L41-L45):

``` clojure
(def ^:private aleph-available?
  (try
    (require '[aleph.http])
    true
    (catch java.io.FileNotFoundException _ false)))
```

The difference of this approach and providing Aleph-aware versions of the middleware you mentioned is basically enhancing behavior of something vs providing something broken if an optional dependency is missing.

**Comment by camdez** [comment]
Hey @muhuk,

Thanks a bunch for the comment! I agree that that approach would be great, though I'm skeptical of what kind of adoption rate we'd get from package maintainers who didn't use Aleph themselves. This parallels the challenge core.typed faced (who wants to deal with maintaining type annotations they don't actually use, especially when it's not even obvious to the maintainer if the code is still correct?). But hopefully we'll see increased adoption of Aleph and this won't be an issue.

Thanks again!

**Comment by muhuk** [comment]
> I'm skeptical of what kind of adoption rate we'd get from package maintainers

I wouldn't worry too much about that.

What matters is how much _you_ care to invest. You can offer a PR and if it's not accepted, you can fork those projects. It's not like these are huge projects and forking would hurt the community etc. etc.

(I have no idea which projects contain those middleware BTW)
